# Generated by Django 6.0.5 on 2026-05-19 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Well',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(blank=True, max_length=25, null=True, verbose_name='Регион')),
                ('name_mst', models.CharField(blank=True, max_length=100, null=True, verbose_name='Месторождение')),
                ('plosh', models.CharField(blank=True, max_length=256, null=True, verbose_name='Площадь')),
                ('n_lic', models.CharField(blank=True, max_length=25, null=True, verbose_name='Номер лицензии')),
                ('lic', models.CharField(blank=True, max_length=256, null=True, verbose_name='Название лицензионного участка')),
                ('n_kust', models.CharField(blank=True, max_length=25, null=True, verbose_name='Номер куста')),
                ('n_skv', models.CharField(blank=True, max_length=10, null=True, verbose_name='Номер скважины')),
                ('tip_skv', models.CharField(blank=True, max_length=25, null=True, verbose_name='Тип скважины')),
                ('sk_zb', models.FloatField(blank=True, null=True, verbose_name='Отметка забоя, м')),
                ('altit', models.FloatField(blank=True, null=True, verbose_name='Альтитуда ротора, м')),
                ('d_zaboi', models.FloatField(blank=True, null=True, verbose_name='Давление забоя, МПа')),
                ('d_plast', models.FloatField(blank=True, null=True, verbose_name='Давление пластовое, МПа')),
                ('d_skv', models.FloatField(blank=True, null=True, verbose_name='Диаметр скважины, мм')),
                ('x', models.CharField(blank=True, max_length=50, null=True, verbose_name='Координата X')),
                ('y', models.CharField(blank=True, max_length=50, null=True, verbose_name='Координата Y')),
                ('id_strat', models.CharField(blank=True, max_length=9, null=True, verbose_name='Индекс пласта')),
                ('strat', models.CharField(blank=True, max_length=100, null=True, verbose_name='Название пласта')),
                ('abs_o_k', models.FloatField(blank=True, null=True, verbose_name='Абсолютная отметка кровли, м')),
                ('abs_o_p', models.FloatField(blank=True, null=True, verbose_name='Абсолютная отметка подошвы, м')),
                ('shtucr', models.FloatField(blank=True, null=True, verbose_name='Штутцер, мм')),
                ('debit_n', models.FloatField(blank=True, null=True, verbose_name='Дебит нефти, т/сут')),
                ('uvp_n', models.FloatField(blank=True, null=True, verbose_name='Удельный вес нефти, т/м3')),
                ('debit_v', models.FloatField(blank=True, null=True, verbose_name='Дебит воды, т/сут')),
                ('debit_g', models.FloatField(blank=True, null=True, verbose_name='Дебит газа, куб.м/сут')),
                ('debit_k', models.FloatField(blank=True, null=True, verbose_name='Дебит конденсата, т/сут')),
                ('char_nas', models.CharField(blank=True, max_length=50, null=True, verbose_name='Характер насыщения')),
                ('m_otl', models.FloatField(blank=True, null=True, verbose_name='Эффективная мощность отложений, м')),
                ('o_rab', models.DateField(blank=True, null=True, verbose_name='Дата окончания бурения')),
                ('id_xy', models.CharField(blank=True, max_length=50, null=True, verbose_name='ID_XY')),
                ('auth', models.CharField(blank=True, max_length=50, null=True, verbose_name='Автор записи')),
                ('material_available', models.CharField(blank=True, max_length=50, null=True, verbose_name='Наличие материала')),
            ],
            options={
                'verbose_name': 'Скважина',
                'verbose_name_plural': 'Скважины',
            },
        ),
    ]
