# Generated by Django 6.0.5 on 2026-05-19 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='well',
            name='id_strat',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Индекс пласта'),
        ),
    ]
